Repository Team1559/DevilScout, pull requests merged in 2024-02, with the labels that each got.

#19 Improve frc red/blue, slight UI tweaks
  lib/components/match_card.dart
  lib/components/team_card.dart
  lib/pages/manage.dart
  lib/pages/select_drive_team.dart
  lib/pages/select_match.dart
  lib/pages/select_pit.dart
  lib/theme.dart
Labels: cleanup, feature

#20 Fix UserEditDialog overflow on settings page
  lib/components/user_edit_dialog.dart
Labels: bug

#21 Functional team analysis page (not pretty)
  lib/components/analysis.dart
  lib/components/menu_scaffold.dart
  lib/components/questions.dart
  lib/components/radar_chart.dart
  lib/pages/analyze_team.dart
  lib/pages/select_match.dart
  lib/pages/select_team.dart
  lib/server/analysis.dart
  lib/server/auth.dart
  lib/theme.dart
  pubspec.yaml
Labels: feature

#22 Add about & technical pages
  lib/components/menu_scaffold.dart
  lib/components/no_event_set.dart
  lib/components/user_edit_dialog.dart
  lib/main.dart
  lib/pages/analyze/analyze_team.dart
  lib/pages/analyze/select_team.dart
  lib/pages/login/load_session.dart
  lib/pages/login/login.dart
  lib/pages/management/manage.dart
  lib/pages/scout/scout_drive_team.dart
  lib/pages/scout/scout_match.dart
  lib/pages/scout/scout_pit.dart
  lib/pages/scout/select_drive_team.dart
  lib/pages/scout/select_match.dart
  lib/pages/scout/select_pit.dart
  lib/pages/settings/about.dart
  lib/pages/settings/legal.dart
  lib/pages/settings/settings.dart
  lib/pages/settings/technical.dart
  lib/server/server.dart
  pubspec.yaml
Labels: feature

#24 Update README.md with some screenshots
  README.md
Labels: documentation

#23 Add indicator for when no matches are on TBA
  lib/pages/scout/select_match.dart
Labels: feature

#25 Decrease select page padding, fix horizontal page bug, consolidate code
  lib/components/analysis.dart
  lib/components/horizontal_view.dart
  lib/components/menu_scaffold.dart
  lib/components/questions.dart
  lib/pages/analyze/analyze_team.dart
  lib/pages/analyze/select_team.dart
  lib/pages/scout/select_drive_team.dart
  lib/pages/scout/select_match.dart
  lib/pages/scout/select_pit.dart
Labels: bug, cleanup

#28 Unify gh actions workflows
  .github/workflows/flutter-build.yml
Labels: cleanup, testing

#26 Increase overscroll for questions, analysis
  lib/components/analysis.dart
  lib/components/questions.dart
Labels: ui

#29 Fix team select bug
  lib/pages/scout/select_match.dart
Labels: bug

#27 Add preliminary app icon
  .github/workflows/flutter-build.yml
  .gitignore
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  assets/icon.png
  flutter_launcher_icons.yaml
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/README.md
  pubspec.yaml
Labels: feature

#30 Update analysis api
  lib/components/analysis.dart
  lib/pages/analyze/analyze_team.dart
  lib/pages/analyze/select_team.dart
  lib/server/analysis.dart
  lib/server/auth.dart
  lib/server/server.dart
Labels: feature

#31 Change server questions URI
  lib/server/questions.dart
  lib/server/server.dart
Labels: bug

#32 Question UI
  lib/components/horizontal_view.dart
  lib/components/questions.dart
  lib/main.dart
  lib/pages/login/login.dart
  lib/pages/scout/scout_match.dart
  lib/pages/scout/select_match.dart
  lib/pages/settings/settings.dart
  lib/theme.dart
Labels: ui

#33 Update iOS build config file
  ios/Runner.xcodeproj/project.pbxproj
Labels: cleanup

#36 Detect server-side logouts on page refresh
  lib/components/logout.dart
  lib/components/menu_scaffold.dart
  lib/components/questions.dart
  lib/components/user_edit_dialog.dart
  lib/pages/analyze/select_team.dart
  lib/pages/login/load_session.dart
  lib/pages/management/manage.dart
  lib/pages/scout/scout_drive_team.dart
  lib/pages/scout/scout_match.dart
  lib/pages/scout/scout_pit.dart
  lib/pages/scout/select_drive_team.dart
  lib/pages/scout/select_match.dart
  lib/pages/scout/select_pit.dart
  lib/pages/settings/settings.dart
  lib/server/auth.dart
  lib/server/events.dart
  lib/server/server.dart
Labels: feature

#37 UI finalization
  lib/components/questions.dart
  lib/pages/management/manage.dart
Labels: ui

#38 Fix server url (again)
  lib/server/server.dart
Labels: bug
