Repository Team1559/DevilScout, pull requests merged in 2024-03, with the labels that each got.

#48 Add 'Hide Completed' button on match select page
  lib/pages/scout/select_match.dart
Labels: feature

#47 Reduce theme redundancy
  lib/main.dart
  lib/theme.dart
Labels: cleanup

#46 Remove unused RadarChart parameters
  lib/components/analysis.dart
  lib/components/radar_chart.dart
Labels: cleanup

#45 Change red alliance to appear on top of blue alliance
  lib/components/match_card.dart
  lib/pages/scout/select_match.dart
Labels: ui

#44 Changes during first ever internal testing
  .gitignore
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/components/analysis.dart
  lib/components/horizontal_view.dart
  lib/components/questions.dart
  lib/pages/analyze/analyze_team.dart
  lib/pages/scout/scout_match.dart
  lib/pages/scout/scout_pit.dart
  lib/pages/scout/select_drive_team.dart
  lib/pages/scout/select_match.dart
  lib/pages/scout/select_pit.dart
  lib/theme.dart
Labels: bug, cleanup, feature, testing, ui

#50 Change LargeTextField to TextField with decoration overrides
  lib/components/text_field.dart
  lib/components/user_edit_dialog.dart
  lib/pages/login/login.dart
Labels: cleanup

#49 Break MenuScaffold into smaller widgets for performance
  lib/components/menu_scaffold.dart
Labels: bug, cleanup

#51 Don't copy every single parameter from light theme (BAD)
  lib/theme.dart
Labels: bug

#52 Better titles
  lib/pages/analyze/select_team.dart
  lib/pages/scout/select_drive_team.dart
  lib/pages/scout/select_match.dart
  lib/pages/scout/select_pit.dart
Labels: ui

#53 Single submission dialog
  lib/components/questions.dart
Labels: feature

#54 Loading overlay visible while waiting for login
  lib/components/snackbar.dart
  lib/pages/login/login.dart
Labels: feature

#55 Reinitialize Flutter for framework upgrade
  .gitignore
  .vscode/launch.json
  analysis_options.yaml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/example/devil_scout/MainActivity.kt
  android/app/src/main/kotlin/org/victorrobotics/scouting/devilscout/MainActivity.kt
  android/build.gradle
  android/gradle.properties
  android/settings.gradle
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
Labels: cleanup

#56 Put opacity on color instead of widget
  lib/components/loading_overlay.dart
Labels: Performance

#57 In-app notification overlay instead of snackbar
  .gitignore
  ios/Podfile.lock
  lib/components/notification.dart
  lib/components/snackbar.dart
  lib/components/user_edit_dialog.dart
  lib/main.dart
  lib/pages/login/login.dart
  lib/server/server.dart
  pubspec.yaml
Labels: ui

#58 Update app icon
  assets/icon.png
Labels: ui

#59 Remove legal page
  android/app/build.gradle
  lib/pages/settings/settings.dart
  pubspec.yaml
Labels: cleanup

#60 Create issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#61 Clear cached data on event change or server logout
  lib/components/logout.dart
  lib/server/auth.dart
  lib/server/server.dart
Labels: bug

#62 Null safety
  lib/components/match_card.dart
  lib/components/menu_scaffold.dart
  lib/components/no_event_set.dart
  lib/pages/analyze/select_team.dart
  lib/pages/login/login.dart
  lib/pages/management/manage.dart
  lib/pages/scout/scout_drive_team.dart
  lib/pages/scout/scout_pit.dart
  lib/pages/scout/select_drive_team.dart
  lib/pages/scout/select_match.dart
  lib/pages/scout/select_pit.dart
  lib/pages/settings/settings.dart
  lib/server/analysis.dart
  lib/server/events.dart
  lib/server/questions.dart
  lib/server/server.dart
  lib/server/session.dart
  lib/server/session_file.dart
  lib/server/teams.dart
  lib/server/users.dart
Labels: cleanup
